apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: 813169d682d6cd30f90eba6560f1604fe376c588
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: iwiick-app-1-main
      imagePullPolicy: Always
      imageRegistry: 272133924862.dkr.ecr.us-east-1.amazonaws.com/iwiick
      credentialId: credential_fb731b34-238e-4dfb-970d-b42e8f3d9a6b
      commitDetails:
        commitHash: 813169d682d6cd30f90eba6560f1604fe376c588
        commitAvatar: https://github.com/skyu-v2-dev[bot].png
        commitTime: '2024-03-05T11:25:22Z'
        commitMessage: Skyu container Template Workflows Created
        commitUser: skyu-v2-dev[bot]
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: iwiick-app-1
    version: v1.0.0
    applicationId: app_3da30b8d-8704-4f98-ba59-39cbde5b0784
    projectId: project_d858d780-1e39-47ce-aa40-057e703a5f92
    organizationId: org_66955b30-1a63-4c92-bd87-67a900920d99
    environmentId: env_584d4768-bcd6-4f39-ab9f-a3bbaa58b1ca
    environmentName: prod
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: iwiick-app-1
  serviceType: ClusterIP
  version: v1.0.0
  namespace: iwiick-proj-2-prod
